version: '3'

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend
  helper:
    taskfile: ./helper/Taskfile.yml
    dir: ./helper
  infrastructure:
    taskfile: ./infrastructure/Taskfile.yml
    dir: ./infrastructure
  e2e:
    taskfile: ./e2e/Taskfile.yml
    dir: ./e2e

silent: true

tasks:
  lint:
    cmds:
      - task: backend:lint